package com.pltech.lrouter_compiler

/**
 *
 * Created by Pang Li on 2020/12/29
 */
object Constants {
    //for generate
    const val SEPARATOR = "_"
    const val PROJECT = "LRouter"
    const val TAG = "$PROJECT::"
    const val WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER."
    const val METHOD_REGISTER = "register"
    const val METHOD_INJECT = "inject"

    // System interface
    const val ACTIVITY = "android.app.Activity"
    const val FRAGMENT = "android.app.Fragment"
    const val FRAGMENT_V4 = "android.support.v4.app.Fragment"
    const val PARCELABLE = "android.os.Parcelable"

    // Java type
    private const val LANG = "java.lang"
    const val BYTE = "$LANG.Byte"
    const val SHORT = "$LANG.Short"
    const val INTEGER = "$LANG.Integer"
    const val LONG = "$LANG.Long"
    const val FLOAT = "$LANG.Float"
    const val DOUBLE = "$LANG.Double"
    const val BOOLEAN = "$LANG.Boolean"
    const val CHAR = "$LANG.Character"
    const val STRING = "$LANG.String"
    const val SERIALIZABLE = "java.io.Serializable"

    const val PACKAGE_NAME = "com.pltech.lrouter"
    const val IROUTE_PACKAGE = "$PACKAGE_NAME.IRoute"
    const val GENERATED_PACKAGE = "$PACKAGE_NAME.generated"

    // Log
    const val PREFIX_OF_LOGGER: String = "$PROJECT::Compiler "
    const val NO_MODULE_NAME_TIPS = "These is no module name, at 'build.gradle', like :\n" +
            "android {\n" +
            "    defaultConfig {\n" +
            "        ...\n" +
            "        javaCompileOptions {\n" +
            "            annotationProcessorOptions {\n" +
            "                arguments = [AROUTER_MODULE_NAME: project.getName()]\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}\n"
}